// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJpT0jtC_s3Hbc4EMXuyblscrXifvY-0',
    appId: '1:796793370391:web:42f40f3561e792a8686952',
    messagingSenderId: '796793370391',
    projectId: 'csc-message-5ea31',
    authDomain: 'csc-message-5ea31.firebaseapp.com',
    storageBucket: 'csc-message-5ea31.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJpT0jtC_s3Hbc4EMXuyblscrXifvY-0',
    appId: '1:796793370391:web:1a87cd7426f5c9e0686952',
    messagingSenderId: '796793370391',
    projectId: 'csc-message-5ea31',
    authDomain: 'csc-message-5ea31.firebaseapp.com',
    storageBucket: 'csc-message-5ea31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Cd83X0U1km055LbcKlPzcTTohLry-b0',
    appId: '1:796793370391:ios:183bc0d18de7c7e7686952',
    messagingSenderId: '796793370391',
    projectId: 'csc-message-5ea31',
    storageBucket: 'csc-message-5ea31.firebasestorage.app',
    iosBundleId: 'com.example.finalCscApp',
  );

}